export type CastStatus = "waiting" | "moving" | "serving" | "off";
export type CastAttendanceStatus = "present" | "late" | "absent" | "leftEarly";
export type CastShift = { date:string; start:string; end:string; working:boolean; attendance?:CastAttendanceStatus; };
export type OrderStatus = "accepted" | "dispatching" | "serving" | "completed" | "cancelled";
export type Cast = {
  id:string;
  name:string;
  status:CastStatus;
  availableAt?:string;
  shiftStart?:string;
  shiftEnd?:string;
  scheduledToday?:boolean;
  schedule?:CastShift[];
  visible?:boolean;
  unitPrice?:number;
  freeUnitPrice?:number;
  photoUnitPrice?:number;
  repeatUnitPrice?:number;
  ngDetails?:string[];
  availableOptions?:string[];
  notes?:string;
  interviewEvaluation?:string;
  age?:number;
  heightCm?:number;
  bustCm?:number;
  waistCm?:number;
  hipCm?:number;
  cupSize?:string;
};
export type Driver = { id:string; name:string; phone?:string; vehicle?:string; plate?:string; notes?:string; active:boolean; };
export type Course = { id:string; minutes:number; price:number; };
export type Hotel = { id:string; name:string; travelFee:number; visible?:boolean; };
export type Staff = { id:string; name:string; displayName:string; loginId:string; notes?:string; active?:boolean; };
export type StoreOption = { id:string; name:string; price:number; notes?:string; active?:boolean; };
export type Customer = { id:string; phone:string; name?:string; notes?:string; ngInfo?:string; active?:boolean; };
export type PricingConfig = {
  courses:Course[];
  photoNominationFee:number;
  repeatNominationFee:number;
  defaultTravelFee:number;
  extensionMinutes:number;
  extensionPrice:number;
};
export type StaffPermission = {
  staffId:string;
  reception:boolean;
  orders:boolean;
  sales:boolean;
  settings:boolean;
};
export type AuditLog = {
  id:string;
  createdAt:string;
  actor:string;
  category:string;
  action:string;
  detail?:string;
};
export type Order = {
  id:string; createdAt:string; customerPhone:string; locationType:"hotel"|"home";
  locationName:string; room?:string; castId:string; castName:string; driverId?:string; driverName?:string;
  courseMinutes:number; nominationType:"free"|"photo"|"repeat"; selectedOptions?:string[]; optionsTotal:number; travelFee:number;
  discount:number; adjustment:number; total:number; status:OrderStatus; scheduledStart:string; scheduledEnd:string; note?:string;
};
